// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressPlayer.proto

package com.task.entity;

public final class Player {
  private Player() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Player1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Player1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *战斗力
     * </pre>
     *
     * <code>double fight = 1;</code>
     * @return The fight.
     */
    double getFight();

    /**
     * <pre>
     *攻击
     * </pre>
     *
     * <code>float attack = 2;</code>
     * @return The attack.
     */
    float getAttack();

    /**
     * <pre>
     *防御
     * </pre>
     *
     * <code>float desense = 3;</code>
     * @return The desense.
     */
    float getDesense();

    /**
     * <pre>
     *血量
     * </pre>
     *
     * <code>float blood = 4;</code>
     * @return The blood.
     */
    float getBlood();

    /**
     * <pre>
     *攻速
     * </pre>
     *
     * <code>float speed = 5;</code>
     * @return The speed.
     */
    float getSpeed();

    /**
     * <pre>
     *移动
     * </pre>
     *
     * <code>float move = 6;</code>
     * @return The move.
     */
    float getMove();

    /**
     * <pre>
     *阵营
     * </pre>
     *
     * <code>string position = 7;</code>
     * @return The position.
     */
    java.lang.String getPosition();
    /**
     * <pre>
     *阵营
     * </pre>
     *
     * <code>string position = 7;</code>
     * @return The bytes for position.
     */
    com.google.protobuf.ByteString
        getPositionBytes();
  }
  /**
   * Protobuf type {@code Player1}
   */
  public static final class Player1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Player1)
      Player1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Player1.newBuilder() to construct.
    private Player1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Player1() {
      position_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Player1();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Player1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              fight_ = input.readDouble();
              break;
            }
            case 21: {

              attack_ = input.readFloat();
              break;
            }
            case 29: {

              desense_ = input.readFloat();
              break;
            }
            case 37: {

              blood_ = input.readFloat();
              break;
            }
            case 45: {

              speed_ = input.readFloat();
              break;
            }
            case 53: {

              move_ = input.readFloat();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              position_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.task.entity.Player.internal_static_Player1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.task.entity.Player.internal_static_Player1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.task.entity.Player.Player1.class, com.task.entity.Player.Player1.Builder.class);
    }

    public static final int FIGHT_FIELD_NUMBER = 1;
    private double fight_;
    /**
     * <pre>
     *战斗力
     * </pre>
     *
     * <code>double fight = 1;</code>
     * @return The fight.
     */
    @java.lang.Override
    public double getFight() {
      return fight_;
    }

    public static final int ATTACK_FIELD_NUMBER = 2;
    private float attack_;
    /**
     * <pre>
     *攻击
     * </pre>
     *
     * <code>float attack = 2;</code>
     * @return The attack.
     */
    @java.lang.Override
    public float getAttack() {
      return attack_;
    }

    public static final int DESENSE_FIELD_NUMBER = 3;
    private float desense_;
    /**
     * <pre>
     *防御
     * </pre>
     *
     * <code>float desense = 3;</code>
     * @return The desense.
     */
    @java.lang.Override
    public float getDesense() {
      return desense_;
    }

    public static final int BLOOD_FIELD_NUMBER = 4;
    private float blood_;
    /**
     * <pre>
     *血量
     * </pre>
     *
     * <code>float blood = 4;</code>
     * @return The blood.
     */
    @java.lang.Override
    public float getBlood() {
      return blood_;
    }

    public static final int SPEED_FIELD_NUMBER = 5;
    private float speed_;
    /**
     * <pre>
     *攻速
     * </pre>
     *
     * <code>float speed = 5;</code>
     * @return The speed.
     */
    @java.lang.Override
    public float getSpeed() {
      return speed_;
    }

    public static final int MOVE_FIELD_NUMBER = 6;
    private float move_;
    /**
     * <pre>
     *移动
     * </pre>
     *
     * <code>float move = 6;</code>
     * @return The move.
     */
    @java.lang.Override
    public float getMove() {
      return move_;
    }

    public static final int POSITION_FIELD_NUMBER = 7;
    private volatile java.lang.Object position_;
    /**
     * <pre>
     *阵营
     * </pre>
     *
     * <code>string position = 7;</code>
     * @return The position.
     */
    @java.lang.Override
    public java.lang.String getPosition() {
      java.lang.Object ref = position_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        position_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *阵营
     * </pre>
     *
     * <code>string position = 7;</code>
     * @return The bytes for position.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPositionBytes() {
      java.lang.Object ref = position_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        position_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(fight_) != 0) {
        output.writeDouble(1, fight_);
      }
      if (java.lang.Float.floatToRawIntBits(attack_) != 0) {
        output.writeFloat(2, attack_);
      }
      if (java.lang.Float.floatToRawIntBits(desense_) != 0) {
        output.writeFloat(3, desense_);
      }
      if (java.lang.Float.floatToRawIntBits(blood_) != 0) {
        output.writeFloat(4, blood_);
      }
      if (java.lang.Float.floatToRawIntBits(speed_) != 0) {
        output.writeFloat(5, speed_);
      }
      if (java.lang.Float.floatToRawIntBits(move_) != 0) {
        output.writeFloat(6, move_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(position_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, position_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(fight_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, fight_);
      }
      if (java.lang.Float.floatToRawIntBits(attack_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, attack_);
      }
      if (java.lang.Float.floatToRawIntBits(desense_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, desense_);
      }
      if (java.lang.Float.floatToRawIntBits(blood_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, blood_);
      }
      if (java.lang.Float.floatToRawIntBits(speed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, speed_);
      }
      if (java.lang.Float.floatToRawIntBits(move_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, move_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(position_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, position_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.task.entity.Player.Player1)) {
        return super.equals(obj);
      }
      com.task.entity.Player.Player1 other = (com.task.entity.Player.Player1) obj;

      if (java.lang.Double.doubleToLongBits(getFight())
          != java.lang.Double.doubleToLongBits(
              other.getFight())) return false;
      if (java.lang.Float.floatToIntBits(getAttack())
          != java.lang.Float.floatToIntBits(
              other.getAttack())) return false;
      if (java.lang.Float.floatToIntBits(getDesense())
          != java.lang.Float.floatToIntBits(
              other.getDesense())) return false;
      if (java.lang.Float.floatToIntBits(getBlood())
          != java.lang.Float.floatToIntBits(
              other.getBlood())) return false;
      if (java.lang.Float.floatToIntBits(getSpeed())
          != java.lang.Float.floatToIntBits(
              other.getSpeed())) return false;
      if (java.lang.Float.floatToIntBits(getMove())
          != java.lang.Float.floatToIntBits(
              other.getMove())) return false;
      if (!getPosition()
          .equals(other.getPosition())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getFight()));
      hash = (37 * hash) + ATTACK_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAttack());
      hash = (37 * hash) + DESENSE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDesense());
      hash = (37 * hash) + BLOOD_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBlood());
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSpeed());
      hash = (37 * hash) + MOVE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMove());
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.task.entity.Player.Player1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.task.entity.Player.Player1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.task.entity.Player.Player1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.task.entity.Player.Player1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.task.entity.Player.Player1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.task.entity.Player.Player1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.task.entity.Player.Player1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.task.entity.Player.Player1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.task.entity.Player.Player1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.task.entity.Player.Player1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.task.entity.Player.Player1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.task.entity.Player.Player1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.task.entity.Player.Player1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Player1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Player1)
        com.task.entity.Player.Player1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.task.entity.Player.internal_static_Player1_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.task.entity.Player.internal_static_Player1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.task.entity.Player.Player1.class, com.task.entity.Player.Player1.Builder.class);
      }

      // Construct using com.task.entity.Player.Player1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fight_ = 0D;

        attack_ = 0F;

        desense_ = 0F;

        blood_ = 0F;

        speed_ = 0F;

        move_ = 0F;

        position_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.task.entity.Player.internal_static_Player1_descriptor;
      }

      @java.lang.Override
      public com.task.entity.Player.Player1 getDefaultInstanceForType() {
        return com.task.entity.Player.Player1.getDefaultInstance();
      }

      @java.lang.Override
      public com.task.entity.Player.Player1 build() {
        com.task.entity.Player.Player1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.task.entity.Player.Player1 buildPartial() {
        com.task.entity.Player.Player1 result = new com.task.entity.Player.Player1(this);
        result.fight_ = fight_;
        result.attack_ = attack_;
        result.desense_ = desense_;
        result.blood_ = blood_;
        result.speed_ = speed_;
        result.move_ = move_;
        result.position_ = position_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.task.entity.Player.Player1) {
          return mergeFrom((com.task.entity.Player.Player1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.task.entity.Player.Player1 other) {
        if (other == com.task.entity.Player.Player1.getDefaultInstance()) return this;
        if (other.getFight() != 0D) {
          setFight(other.getFight());
        }
        if (other.getAttack() != 0F) {
          setAttack(other.getAttack());
        }
        if (other.getDesense() != 0F) {
          setDesense(other.getDesense());
        }
        if (other.getBlood() != 0F) {
          setBlood(other.getBlood());
        }
        if (other.getSpeed() != 0F) {
          setSpeed(other.getSpeed());
        }
        if (other.getMove() != 0F) {
          setMove(other.getMove());
        }
        if (!other.getPosition().isEmpty()) {
          position_ = other.position_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.task.entity.Player.Player1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.task.entity.Player.Player1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double fight_ ;
      /**
       * <pre>
       *战斗力
       * </pre>
       *
       * <code>double fight = 1;</code>
       * @return The fight.
       */
      @java.lang.Override
      public double getFight() {
        return fight_;
      }
      /**
       * <pre>
       *战斗力
       * </pre>
       *
       * <code>double fight = 1;</code>
       * @param value The fight to set.
       * @return This builder for chaining.
       */
      public Builder setFight(double value) {
        
        fight_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *战斗力
       * </pre>
       *
       * <code>double fight = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFight() {
        
        fight_ = 0D;
        onChanged();
        return this;
      }

      private float attack_ ;
      /**
       * <pre>
       *攻击
       * </pre>
       *
       * <code>float attack = 2;</code>
       * @return The attack.
       */
      @java.lang.Override
      public float getAttack() {
        return attack_;
      }
      /**
       * <pre>
       *攻击
       * </pre>
       *
       * <code>float attack = 2;</code>
       * @param value The attack to set.
       * @return This builder for chaining.
       */
      public Builder setAttack(float value) {
        
        attack_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *攻击
       * </pre>
       *
       * <code>float attack = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttack() {
        
        attack_ = 0F;
        onChanged();
        return this;
      }

      private float desense_ ;
      /**
       * <pre>
       *防御
       * </pre>
       *
       * <code>float desense = 3;</code>
       * @return The desense.
       */
      @java.lang.Override
      public float getDesense() {
        return desense_;
      }
      /**
       * <pre>
       *防御
       * </pre>
       *
       * <code>float desense = 3;</code>
       * @param value The desense to set.
       * @return This builder for chaining.
       */
      public Builder setDesense(float value) {
        
        desense_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *防御
       * </pre>
       *
       * <code>float desense = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDesense() {
        
        desense_ = 0F;
        onChanged();
        return this;
      }

      private float blood_ ;
      /**
       * <pre>
       *血量
       * </pre>
       *
       * <code>float blood = 4;</code>
       * @return The blood.
       */
      @java.lang.Override
      public float getBlood() {
        return blood_;
      }
      /**
       * <pre>
       *血量
       * </pre>
       *
       * <code>float blood = 4;</code>
       * @param value The blood to set.
       * @return This builder for chaining.
       */
      public Builder setBlood(float value) {
        
        blood_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *血量
       * </pre>
       *
       * <code>float blood = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlood() {
        
        blood_ = 0F;
        onChanged();
        return this;
      }

      private float speed_ ;
      /**
       * <pre>
       *攻速
       * </pre>
       *
       * <code>float speed = 5;</code>
       * @return The speed.
       */
      @java.lang.Override
      public float getSpeed() {
        return speed_;
      }
      /**
       * <pre>
       *攻速
       * </pre>
       *
       * <code>float speed = 5;</code>
       * @param value The speed to set.
       * @return This builder for chaining.
       */
      public Builder setSpeed(float value) {
        
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *攻速
       * </pre>
       *
       * <code>float speed = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeed() {
        
        speed_ = 0F;
        onChanged();
        return this;
      }

      private float move_ ;
      /**
       * <pre>
       *移动
       * </pre>
       *
       * <code>float move = 6;</code>
       * @return The move.
       */
      @java.lang.Override
      public float getMove() {
        return move_;
      }
      /**
       * <pre>
       *移动
       * </pre>
       *
       * <code>float move = 6;</code>
       * @param value The move to set.
       * @return This builder for chaining.
       */
      public Builder setMove(float value) {
        
        move_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *移动
       * </pre>
       *
       * <code>float move = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMove() {
        
        move_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object position_ = "";
      /**
       * <pre>
       *阵营
       * </pre>
       *
       * <code>string position = 7;</code>
       * @return The position.
       */
      public java.lang.String getPosition() {
        java.lang.Object ref = position_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          position_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *阵营
       * </pre>
       *
       * <code>string position = 7;</code>
       * @return The bytes for position.
       */
      public com.google.protobuf.ByteString
          getPositionBytes() {
        java.lang.Object ref = position_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          position_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *阵营
       * </pre>
       *
       * <code>string position = 7;</code>
       * @param value The position to set.
       * @return This builder for chaining.
       */
      public Builder setPosition(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        position_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *阵营
       * </pre>
       *
       * <code>string position = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosition() {
        
        position_ = getDefaultInstance().getPosition();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *阵营
       * </pre>
       *
       * <code>string position = 7;</code>
       * @param value The bytes for position to set.
       * @return This builder for chaining.
       */
      public Builder setPositionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        position_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Player1)
    }

    // @@protoc_insertion_point(class_scope:Player1)
    private static final com.task.entity.Player.Player1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.task.entity.Player.Player1();
    }

    public static com.task.entity.Player.Player1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Player1>
        PARSER = new com.google.protobuf.AbstractParser<Player1>() {
      @java.lang.Override
      public Player1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Player1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Player1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Player1> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.task.entity.Player.Player1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Player1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Player1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023addressPlayer.proto\"w\n\007Player1\022\r\n\005figh" +
      "t\030\001 \001(\001\022\016\n\006attack\030\002 \001(\002\022\017\n\007desense\030\003 \001(\002" +
      "\022\r\n\005blood\030\004 \001(\002\022\r\n\005speed\030\005 \001(\002\022\014\n\004move\030\006" +
      " \001(\002\022\020\n\010position\030\007 \001(\tB\031\n\017com.task.entit" +
      "yB\006Playerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Player1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Player1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Player1_descriptor,
        new java.lang.String[] { "Fight", "Attack", "Desense", "Blood", "Speed", "Move", "Position", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
